CLEAR SCREEN;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

DROP TABLE Player_info CASCADE CONSTRAINTS;
DROP TABLE Question_Gallery2 CASCADE CONSTRAINTS;
DROP TABLE Asking2 CASCADE CONSTRAINTS;
DROP TABLE Answer3 CASCADE CONSTRAINTS;
DROP TABLE Answer4 CASCADE CONSTRAINTS;
DROP TABLE Score CASCADE CONSTRAINTS;

CREATE TABLE Player_info(PID INTEGER, NAME VARCHAR2(50), AGE INTEGER, GENDER VARCHAR2(10), MOBILE INTEGER,
					   PRIMARY KEY(PID));

CREATE TABLE Question_Gallery2(QID INTEGER, RID INTEGER, MARKS INTEGER, QUESTION VARCHAR2(500), OID INTEGER);

CREATE TABLE Asking2(QID INTEGER, MARKS INTEGER, QUESTION VARCHAR2(500));
					 
CREATE TABLE Answer3(QID INTEGER, RESULT_STATUS VARCHAR2(15));
					 
CREATE TABLE Answer4(QID INTEGER, RESULT_STATUS VARCHAR2(15));

CREATE TABLE Score(QID INTEGER, GAIN INTEGER, TOTAL_SCORE INTEGER);

INSERT INTO Question_Gallery2 VALUES(1, 1011, 4, 'Capital of Bangladesh ?', 101);
INSERT INTO Question_Gallery2 VALUES(2, 1012, 6, 'Independence year of Bangladesh ?', 102);
INSERT INTO Question_Gallery2 VALUES(3, 1012, 6, 'Founding leader of Bangladesh ?', 103);
INSERT INTO Question_Gallery2 VALUES(4, 1013, 12, 'City of Pakistani surrender in 1971 ?', 104);
INSERT INTO Question_Gallery2 VALUES(5, 1013, 12, 'Name of 1971 military operation ?', 105);
				 
CREATE OR REPLACE TRIGGER PLAYER_INFO_INPUT
BEFORE INSERT ON Player_info
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('THE PLAYER INFO HAS BEEN ADDED');
END;
/

ACCEPT E CHAR PROMPT "PLAYER NAME : ";
ACCEPT F NUMBER PROMPT "AGE : ";
ACCEPT G NUMBER PROMPT "GENDER : 1. MALE	2. FEMALE	??? ";
ACCEPT H NUMBER PROMPT "MOBILE : ";
	
BEGIN
	
	DELETE FROM Player_info;
	IF (&G = 1) THEN
		INSERT INTO Player_info VALUES(10001, '&E', &F, 'MALE', &H);
	ELSIF (&G = 2) THEN
		INSERT INTO Player_info VALUES(10001, '&E', &F, 'FEMALE', &H);
	END IF;

END;
/

COMMIT;